### ISSUE TITLE
Cannot edit blocks on multiplayer server

### ISSUE THREAD

**Issue by Bionic-Dog** [CristalGaming/PuzzleCode#2]
Was messing around in creative on my server--the GUI set does not function correctly, at least with an entity detector. No matter what value I place into the text box, it simple sets the range nbt to 0.0, greatly limiting the use of the blocks from this mod.

**Comment by CristalGaming** [comment]
what version are you playing on?

**Comment by Bionic-Dog** [comment]
1.20.1, neoforge. want a modlist?

**Comment by Bionic-Dog** [comment]
(also, if you're looking for a texture artist, i'd love to help with this mod!)

**Comment by CristalGaming** [comment]
> 1.20.1, neoforge. want a modlist?

The mod wasn't made for neoforge (only forge). Neoforge support will come in 1.21.1.

Edit: I just found out that a version was marked for Neoforge on modrinth by mistake.

>  (also, if you're looking for a texture artist, i'd love to help with this mod!)

Also you can help me with the textures if you want. just tell me what would you modify.
